### PR TITLE
Bump Kafka dependencies

### PR DESCRIPTION
**Pull request by yeikel**

### CODE REVIEW

**Comment by yeikel** [comment]
Opened it to see what the CI thinks but it seems that the workflow needs approval. Can you help here? @vietj

**Comment by vietj** [comment]
@yeikel CI does not seem happy

**Comment by yeikel** [comment]
> @yeikel CI does not seem happy

Thanks. I'll take it from here

**Comment by yeikel** [comment]
@vietj I reduced the scope of the PR to continue with 3.7.x for now while still fixing the active CVEs. 

The upgrade beyond this needs more work

**Comment by yeikel** [comment]
@vietj Can we backport this to 4.x?

**Comment by ppatierno** [comment]
Fine with me!

**Comment by tsegismont** [comment]
> Fine with me!

Thank you @ppatierno 

Then please go ahead @yeikel !

**Comment by yeikel** [comment]
> > Fine with me!
> 
> Thank you @ppatierno
> 
> Then please go ahead @yeikel !

@tsegismont @ppatierno See https://github.com/vert-x3/vertx-kafka-client/pull/283

And thank you!

**Pull request merged**
