### PR TITLE
Add missing properties

### PR DESCRIPTION
**Pull request by jhughes24816**
Motivation:

From the work I previously committed (#217 and #218) I had overlooked adding a couple of properties that are part of the usual Kafka responses to the admin client calls being made here.

This work adds those properties.

@ppatierno @vietj Comments and adjustments welcome, thanks!

### CODE REVIEW

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!

**Review by vietj — APPROVED** [review]
LGTM

**Comment by jhughes24816** [comment]
Glad it passed, just wanted to add this comment:

It seems the testCreatePartitionInTopicWithAssignment is a bit flaky as it sometimes passes/fails? Is there an issue open to address this?

**Comment by vietj** [comment]
@jhughes24816 feel free to open an issue for the flaky test, those are a pain

**Comment by jhughes24816** [comment]
Hi there @ppatierno @vietj Please merge when convenient. Thanks

**Pull request merged**
