### PR TITLE
Admin Client: report close completion

### LINKED ISSUE #192: Kafka Admin Client `close` does not report completion
```
 @Override
  public Future<Void> close(long timeout) {
    ContextInternal ctx = (ContextInternal) vertx.getOrCreateContext();
    Promise<Void> promise = ctx.promise();

    ctx.executeBlocking(prom -> {
      if (timeout > 0) {
        adminClient.close(Duration.ofMillis(timeout));
      } else {
        adminClient.close();
      }
      prom.complete();
    });
    return promise.future();
  }
```

The `executeBlocking` to not report the completion on the right promise.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #192

### CODE REVIEW

**Comment by tsegismont** [comment]
@ppatierno the second commit is not strictly related: it's a small improvement that I've done while checking all asynchronous close methods.

**Review by ppatierno — APPROVED** [review]
Thanks for the PR!

**Comment by ppatierno** [comment]
@tsegismont because there some people and project still using 3.9.x version of this client, do you have any concerns to cherry-pick this to the corresponding branch as well?

**Comment by tsegismont** [comment]
@ppatierno will do

**Pull request merged**
