### PR TITLE
added consumer position method to KafkaStream implementation

### PR DESCRIPTION
**Pull request by maxplanck76er**

### CODE REVIEW

**Comment by maxplanck76er** [comment]
You are right, it is just because of differences in imports organization and code formatting.

I will fix that.

**Comment by vietj** [comment]
@ppatierno ok for merging ?

**Comment by vietj** [comment]
I'd like to make a 3.4.0.Beta1 release

**Comment by ppatierno** [comment]
I was waiting for a squash from @maxplanck76er to avoid useless commits with hundreds of lines added/removed due to only formatting problems.

**Comment by vietj** [comment]
:-)

**Comment by vietj** [comment]
@ppatierno do you know that GitHub has a button "Squash and merge" in the PR :) ?

**Comment by maxplanck76er** [comment]
@ppatierno I have made the squash in this morning : [f780465](https://github.com/vert-x3/vertx-kafka-client/pull/11/commits/f780465b540056c1944579c147376784c4087036)

**Comment by ppatierno** [comment]
@vietj @maxplanck76er I merged the PR thanks ! I have also committed the polyglot KafkaConsumer (and related implementatin) with the same position method using the underlying stream implementation.

**Comment by ppatierno** [comment]
@maxplanck76er great to know about that ! If you have problems please open issues and discussion with us or just contribute ! ;)

**Comment by vietj** [comment]
you can also join the vertx-dev group for discussions @maxplanck76er

**Pull request merged**
