### PR TITLE
Properly override equals() and hashCode() in TopicPartition.java

### PR DESCRIPTION
**Pull request by daka1510**
https://github.com/vert-x3/vertx-kafka-client/issues/96

### CODE REVIEW

**Comment by daka1510** [comment]
@ppatierno - no specific reason to develop it this way. I auto-generated these methods with my IDE (IntelliJ). Feel free to post back with an optimized version if you see good reasons to change it :).

**Comment by vietj** [comment]
@ppatierno looks ok

**Comment by daka1510** [comment]
@ppatierno 
- [X] updated hashCode implementation as proposed
- [X] added unit tests (that fail without our fix and now succeed)

**Comment by daka1510** [comment]
@ppatierno - done.

**Pull request merged**
