### PR TITLE
Update minor versions in pom.xml

### PR DESCRIPTION
**Pull request by neokeld**
Update versions to get last fix et security updates from dependencies.

### CODE REVIEW

**Comment by vietj** [comment]
we can't upgrade the logger dependencies because they are set by default to what the vertx stack uses.

can you tell which transitive dependencies are updated as consequence of the kafka bump ?

**Comment by neokeld** [comment]
The list of transitive dependencies of kafka_2.12 and kafka-clients :
jopt-simple 5.0.4
kafka-clients 1.0.2
lz4-java 1.4
metrics-core 2.2.0
snappy-java 1.1.4
slf4j-api 1.7.25
slf4j-log4j12 1.7.25
zkclient 0.10
zookeeper 3.4.10

Do you want me to provide older versions of these packages?

And sorry I don't see a log4j dependency from vertx-core / -codegen / -docgen

**Comment by ppatierno** [comment]
I would love bumping the Kafka version to the latest 2.0.0. It doesn't make sense having the future Vert.x release with the old 1.0.0.

**Comment by ppatierno** [comment]
Going to close this, because stale.

**Pull request closed without merging**
