### PR TITLE
Ensure that shutdown runs on a different thread

### PR DESCRIPTION
**Pull request by geoand**
This is meant to avoid cases where the Context had already been shutdown

See: https://github.com/quarkusio/quarkus/issues/4834

cc @vietj @cescoffier

### CODE REVIEW

**Comment by geoand** [comment]
I opened this PR against the `3.8` branch but I am not sure it was the correct thing to do...

**Comment by vietj** [comment]
we should have it for master and 3.8 branches

**Comment by vietj** [comment]
can we get a description of what this fundamentally solves and a test ?

**Comment by geoand** [comment]
I'll close this one and recreate against `master`

**Comment by geoand** [comment]
I opened #153 as a follow up

**Pull request closed without merging**
