### PR TITLE
Bump Debezium to version 0.7.3

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
@vietj

**Comment by vietj** [comment]
have you checked if this changes the transitive dependencies ?

**Comment by oscerd** [comment]
I don't see changes between 0.7.1 and 0.7.3

http://search.maven.org/#artifactdetails%7Cio.debezium%7Cdebezium-parent%7C0.7.1%7Cpom
http://search.maven.org/#artifactdetails%7Cio.debezium%7Cdebezium-parent%7C0.7.3%7Cpom

**Comment by oscerd** [comment]
So it should be fine.

**Pull request merged**
