### PR TITLE
Bump Debezium to version 0.7.2

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
still 1.0.0

http://search.maven.org/#artifactdetails%7Cio.debezium%7Cdebezium-parent%7C0.7.2%7Cpom

**Comment by oscerd** [comment]
By the way 1.0.1 is not released yet.

**Comment by ppatierno** [comment]
Yes you are right ;)

**Comment by oscerd** [comment]
Thanks :-)

**Pull request merged**
