### PR TITLE
Bumped Kafka version to 2.3.1

### PR DESCRIPTION
**Pull request by danielprinz**
There is a new bug fix release available:
https://www.apache.org/dist/kafka/2.3.1/RELEASE_NOTES.html

### CODE REVIEW

**Comment by danielprinz** [comment]
Wanted to use the 2.3 version a bit longer so I thought upgrading to the latest one would be good. I define it in my projects explicitly now, there I did not find any dependency issues. Nevertheless I will verify it agains the vertx-stack as you are proposing and open it against master. Thanks!

**Comment by ppatierno** [comment]
@danielprinz any news about this?

**Comment by danielprinz** [comment]
I checked out master and tried to build it. For some reason it is stuck at `Running io.vertx.stack.VertxStacksTest` with no output. Also the maven debug output does not give me insight what is happening. 🤔 Is there some special setup needed @ppatierno ?
I am using the latest openjdk8.

**Comment by danielprinz** [comment]
Closed in favour of updating to 2.4.0 which was released this week.

**Pull request closed without merging**
